name: news_app
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  scoped_model:
  http:
  cached_network_image:
  flutter_spinkit:
  url_launcher:
  shared_preferences:

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
   - assets/images/menu.png
   - assets/images/menuDark.png
   - assets/images/profile.png
   - assets/images/back_arrow.png 
   - assets/images/clock.png 
   - assets/images/author.png 
   - assets/images/authorDark.png
   - assets/images/bookmarked.png 
   - assets/images/unbookmarked.png 
   - assets/images/share.png 
   - assets/images/dark.png
   - assets/images/light.png
   - assets/images/webLink.png
   - assets/images/webLinkDark.png
  fonts:
    - family: Livvic
      fonts:
        - asset: assets/fonts/Livvic/Livvic-Regular.ttf
        - asset: assets/fonts/Livvic/Livvic-RegularItalic.ttf
          style: italic
        - asset: assets/fonts/Livvic/Livvic-Bold.ttf
          weight: 700
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
